from elasticsearch import Elasticsearch

# Elasticsearch connection details.
# The default username is 'elastic', and the password should be the one you set when
# you started Elasticsearch with Docker Compose.
ELASTIC_HOST = 'http://localhost:9200'
ELASTIC_USER = 'elastic'
ELASTIC_PASSWORD = 'nus8jpR*--=6jU1+P6Q7' # Replace with your actual password

def connect_to_elasticsearch():
    """
    Attempts to establish a connection to Elasticsearch.
    """
    try:
        # Create an Elasticsearch client instance with authentication details.
        es = Elasticsearch(
            [ELASTIC_HOST],
            basic_auth=(ELASTIC_USER, ELASTIC_PASSWORD)
        )
        
        # Check if the connection is successful by pinging the cluster.
        if es.ping():
            print("✅ Successfully connected to Elasticsearch!")
            return es
        else:
            print("❌ Failed to connect to Elasticsearch.")
            return None

    except Exception as e:
        print(f"❌ An error occurred during connection: {e}")
        return None

def create_index_if_not_exists(es, index_name):
    """
    Creates a new index if it does not already exist.
    """
    if not es.indices.exists(index=index_name):
        print(f"Creating index '{index_name}'...")
        es.indices.create(index=index_name)
        print("✅ Index created.")
    else:
        print(f"✅ Index '{index_name}' already exists.")

def index_sample_data(es, index_name):
    """
    Adds a sample document to the specified index.
    """
    sample_doc = {
        'review/text': 'This is a sample review text.',
        'review/summary': 'Sample summary',
        'review/score': 5.0
    }
    
    try:
        # Index the document. The ID will be auto-generated by Elasticsearch.
        response = es.index(index=index_name, document=sample_doc)
        print(f"✅ Document indexed successfully: {response['result']}")
    except Exception as e:
        print(f"❌ An error occurred while indexing document: {e}")

if __name__ == "__main__":
    # Get the Elasticsearch client instance.
    es_client = connect_to_elasticsearch()
    
    # Proceed only if the connection was successful.
    if es_client:
        index_name = "amazon_reviews"
        create_index_if_not_exists(es_client, index_name)
        index_sample_data(es_client, index_name)